server:
  port: 8081
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

build:
  version: "1.0"

#  this will be prefix for AccountsContactInfoDto
accounts:
  message: "Welcome to my banking project."
  contactDetails:
    name: "Bickey Manandhar - Developer"
    email: "xyz@gmail.com"
  onCallSupport:
    - (123)456-7891
    - (234)567-8910
